[package]
name = "onvm"
version = "0.1.0"
edition = "2021"
description = "Open Network Virtual Machine"

[dependencies]
anyhow = "1.0"
axum = { version = "0.7", features = ["json"] }
blake3 = "1.5"
bytes = "1.7"
clap = { version = "4.5", features = ["derive"] }
ed25519-dalek = { version = "1", features = ["serde"] }
futures = "0.3"
hex = "0.4"
bincode = { version = "2.0", features = ["serde"] }
base64 = "0.22"
fastcdc = "3.2"
libp2p = { version = "0.53", default-features = false, features = [
    "tcp",
    "dns",
    "websocket",
    "noise",
    "yamux",
    "macros",
    "gossipsub",
    "identify",
    "kad",
    "cbor",
    "request-response",
    "tls",
    "tokio",
    "mdns",
] }
rand = "0.7"
reqwest = { version = "0.12", features = ["json", "rustls-tls", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sled = "0.34"
thiserror = "1.0"
tokio = { version = "1.40", features = ["full"] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.10", features = ["v4", "serde"] }
toml = "0.8"
reed-solomon-erasure = "6"
indicatif = "0.17"
tokio-util = { version = "0.7", features = ["io"] }
num_cpus = "1.16"
sysinfo = "0.32"

wasmtime = { version = "16", features = [
    "async",
    "cache",
    "cranelift",
    "wat",
    "pooling-allocator",
] }
wasmtime-wasi = "16"


[dev-dependencies]
tokio = { version = "1.40", features = ["macros"] }